version: '3'

networks:
  sensustack_public:
    external: true

services:
  sensu_client:
    image: sensustack_sensu
    volumes:
      - ./etc/sensu:/etc/sensu
      - ./sensu_ssl_tool:/etc/ssl:ro
    command: ["/opt/sensu/bin/sensu-client", "-d", "/etc/sensu"]
    networks:
      - sensustack_public
