version: '3'

networks:
  sensu_net:
    driver: bridge

services:
  redis:
    image: redis:4-alpine
    volumes:
      - ./etc/redis:/usr/local/etc/redis:ro
      - ./data/redis:/data
    expose:
      - "6379"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    volumes:
      - ./etc/rabbitmq/rabbitmq.config:/etc/rabbitmq/rabbitmq.config
      - ./data/rabbitmq:/var/lib/rabbitmq
      - ./sensu_ssl_tool:/etc/ssl:ro
    ports:
      - "4369:4369"
      - "5671:5671"
      - "5672:5672"
      - "15671:15671"
      - "25672:25672"

  sensu:
    build: ./build/sensu/.
    depends_on:
      - rabbitmq
      - redis

  sensu_server:
    image: sensustack_sensu
    volumes:
      - ./etc/sensu:/etc/sensu
      - ./sensu_ssl_tool:/etc/ssl:ro
    command: ["/opt/sensu/bin/sensu-server", "-d", "/etc/sensu"]
    depends_on:
      - sensu
      - rabbitmq
      - redis

  sensu_api:
    image: sensustack_sensu
    volumes:
      - ./etc/sensu:/etc/sensu
      - ./sensu_ssl_tool:/etc/ssl:ro
    command: ["/opt/sensu/bin/sensu-api", "-d", "/etc/sensu"]
    depends_on:
      - sensu
      - rabbitmq
      - redis
    expose:
     - "4567"

  sensu_dashboard:
    image: uchiwa/uchiwa
    volumes:
      - ./etc/sensu-dashboard:/config
      - ./sensu_ssl_tool:/etc/ssl:ro
    depends_on:
      - sensu_api
    ports:
      - "3000:3000"
