version: '3'

services:

  redis:
    image: redis:3.2-alpine
    volumes:
      - ./configuration/redis:/usr/local/etc/redis:ro
      - ./data/redis:/data
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    volumes:
      - ./configuration/rabbitmq/rabbitmq.config:/etc/rabbitmq/rabbitmq.config
      - ./data/rabbitmq:/var/lib/rabbitmq
      - ./sensu_ssl_tool:/etc/sensu_ssl:ro
    ports:
      - "4369:4369"
      - "5671:5671"
      - "5672:5672"
      - "15671:15671"
      - "25672:25672"

  sensu:
    build: ./application/sensu/.
    depends_on:
      - rabbitmq
      - redis

  sensu-server:
    image: sensustack_sensu
    volumes:
      - ./configuration/sensu:/etc/sensu
      - ./sensu_ssl_tool:/etc/sensu_ssl:ro
    command: ["/opt/sensu/bin/sensu-server", "-d", "/etc/sensu"]
    depends_on:
      - sensu
      - rabbitmq
      - redis

  sensu-client:
    image: sensustack_sensu
    volumes:
      - ./configuration/sensu:/etc/sensu
      - ./sensu_ssl_tool:/etc/sensu_ssl:ro
    command: ["/opt/sensu/bin/sensu-client", "-d", "/etc/sensu"]
    depends_on:
      - sensu
      - rabbitmq

  sensu-api:
    image: sensustack_sensu
    volumes:
      - ./configuration/sensu:/etc/sensu
      - ./sensu_ssl_tool:/etc/sensu_ssl:ro
    command: ["/opt/sensu/bin/sensu-api", "-d", "/etc/sensu"]
    depends_on:
      - sensu
      - rabbitmq
      - redis
    ports:
     - "4567:4567"

  sensu-dashboard:
    image: uchiwa/uchiwa
    volumes:
      - ./configuration/sensu-dashboard:/config
      - ./sensu_ssl_tool:/etc/sensu_ssl:ro
    depends_on:
      - sensu-api
    ports:
      - "443:3000"

  graphite-carbon:
    build: ./application/graphite-carbon/.
    depends_on:
      - sensu-server
    ports:
      - "2003:2003"
      - "2004:2004"
      - "7002:7002"

  graphite-web:
    build: ./application/graphite-web/.
    depends_on:
      - graphite-carbon
    ports:
      - "80"
      - "443"

  grafana:
    image: grafana/grafana
    environment:
      - GF_SERVER_ROOT_URL=http://127.0.0.1"
      - GF_SECURITY_ADMIN_PASSWORD=secret
    ports:
      - "3000"
    depends_on:
      - graphite-web
